version: "3"
services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - DATE_SERVICE_URL=date-service:50003
      - LOGS_SERVICE_URL=logs-service:50002
      - PAYMENT_SERVICE_URL=payment-service:50005
      - PROFILES_SERVICE_URL=profiles-service:50004
      - USERS_SERVICE_URL=users-service:50001
    depends_on:
      - date_service
      - users_service
      - payment_service
      - profiles_service

  users_service:
    build: ./users-service
    container_name: users-service
    expose:
      - 50001
    env_file:
      - ./users-service/.env
    environment:
      - DB_HOST=host.docker.internal
      - LOG_SERVICE_ADDR=logs-service:50002
      - JWT_SECRET=secret
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - logs_service

  logs_service:
    build: ./logs-service
    container_name: logs-service
    expose:
      - 50002
    env_file:
      - ./logs-service/.env
    environment:
      - DB_HOST=host.docker.internal

  profiles_service:
    build: ./profiles-service
    container_name: profiles-service
    expose:
      - 50004
    env_file:
      - ./profiles-service/.env
    environment:
      - DB_HOST=host.docker.internal
      - USER_SERVICE_ADDR=users-service:50001
      - LOG_SERVICE_ADDR=logs-service:50002
      - PORT=50004
    extra_hosts:
      - "host.docker.internal:host-gateway"

  payment_service:
    build: ./payment-service
    container_name: payment-service
    expose:
      - 50005
    env_file:
      - ./payment-service/.env
    environment:
      - DB_HOST=host.docker.internal
      - USER_SERVICE_ADDR=users-service:50001
      - LOG_SERVICE_ADDR=logs-service:50002
      - PORT=50005
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - user_service

  date_service:
    build: ./date-service
    container_name: date-service
    expose:
      - 50003
    env_file:
      - ./date-service/.env
    environment:
      - DB_HOST=host.docker.internal
      - PROFILE_SERVICE_ADDR=profiles-service:50004
      - USER_SERVICE_ADDR=user-service:50001
      - LOG_SERVICE_ADDR=logs-service:50002
      - PORT=50003
    extra_hosts:
      - "host.docker.internal:host-gateway"
